# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

# Install app
WORKDIR /app
COPY . /app

# Upgrade pip and install dependencies
RUN pip install --no-cache-dir --upgrade pip && \
    pip install --no-cache-dir -e . && \
    pip install --no-cache-dir mcp>=1.2.0 markdown>=3.4.0

# Default command to run the MCP server
ENTRYPOINT ["python", "-m", "tasks_organizer"]
